from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os
import datetime

OUTPUT_DIR = "output_payslips"

def initialize_dir():
    """Creates the output directory if not exists."""
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

def generate_payslip(emp_data, salary_data):
    """Generates a PDF payslip for the employee."""
    initialize_dir()
    
    emp_id = emp_data['ID']
    name = emp_data['Name']
    date_str = datetime.datetime.now().strftime("%Y_%m")
    filename = f"{OUTPUT_DIR}/Payslip_{emp_id}_{date_str}.pdf"
    
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(200, 750, "EMPLOYEE PAYSLIP")
    
    # Company details
    c.setFont("Helvetica", 12)
    c.drawString(50, 720, "Company: Python Student Group 5")
    c.drawString(50, 705, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d')}")
    
    # Line separator
    c.line(50, 690, 550, 690)
    
    # Employee Details
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 660, "Employee Details:")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, 640, f"ID: {emp_id}")
    c.drawString(50, 620, f"Name: {name}")
    c.drawString(50, 600, f"Role: {emp_data['Role']}")
    
    # Salary Details
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 560, "Salary Breakdown:")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, 540, f"Base Salary: ${emp_data['Base_Salary']}")
    c.drawString(50, 520, f"Days Present: {salary_data['days_present']}")
    c.drawString(50, 500, f"Gross Pay: ${salary_data['gross_pay']}")
    c.drawString(50, 480, f"Tax Deducted (5%): ${salary_data['tax']}")
    
    # Final Net Pay
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 440, f"Net Payable Salary: ${salary_data['net_pay']}")
    
    # Footer
    c.line(50, 420, 550, 420)
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(200, 400, "Generated by Python Payroll System")
    
    c.save()
    print(f"Payslip generated: {filename}")
    return filename
